import React,{useState,useId,useRef} from 'react';
import {cn,Intro,Field,Callout,Link,input,action,repository,exportJSON} from './shared.jsx';
export const contributions=[
 {id:'labels',name:'Independent labels',brief:'Review examples without seeing PS results.',outcome:'Completed blind labels, reasons, disagreements and reviewer independence records.',steps:'Get a new frozen packet from a coordinator. Review alone. Download labels and return them privately.',url:repository+'/blob/main/docs/PS-reviewer-start.md',link:'Read reviewer instructions'},
 {id:'accessibility',name:'Phone & accessibility testing',brief:'Try the checker as a real person on a real device.',outcome:'Device/browser version, steps, expected and observed behavior, and assistance needed.',steps:'Try paste/check, offline reopen, Clear and keyboard or screen-reader navigation. Use synthetic text.',url:repository+'/blob/main/docs/independent-review.md',link:'Read the test script'},
 {id:'code',name:'Code & adapters',brief:'Improve a bounded method or delivery route.',outcome:'A focused change with reproducible checks and updated claim boundaries.',steps:'Choose a tag and an observable defect. Read the contribution rules, make a branch, and submit a pull request.',url:repository+'/blob/main/CONTRIBUTING.md',link:'Read contribution rules'},
 {id:'design',name:'Design & wording',brief:'Make one tag easier to understand and use.',outcome:'A before/after example with a usability reason and accessibility checks.',steps:'Pick the confusing interaction or sentence. Show the shorter, clearer alternative and its limits.',url:repository+'/discussions/categories/ideas',link:'Discuss a design proposal'},
 {id:'docs',name:'Documentation & evidence',brief:'Make instructions and evidence independently reproducible.',outcome:'A corrected guide or evidence record with source, date and executed checks.',steps:'Follow the instructions without developer help. Record where they fail and propose a precise correction.',url:repository+'/blob/main/docs/open-validation-path.md',link:'Read the open validation guide'},
];
export default function Assist({tag,initialRole='labels'}){
 const uid=useId(),ref=useRef(null),[role,setRole]=useState(initialRole),[details,setDetails]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState('');const selected=contributions.find(c=>c.id===role)||contributions[0];
 function save(e){e.preventDefault();if(!details.trim()){setError('Describe the contribution you can deliver.');ref.current.focus();return;}setError('');exportJSON('ai-trust-id-contribution.json',{format:'ai-trust-id-contribution-draft/v1',role:selected.id,tag:tag?.id||'PS',deliverable:selected.outcome,proposal:details.trim(),status:'proposal_not_submitted'});setStatus('Proposal downloaded. No task was assigned or submitted. Share it through the public contribution discussion.');}
 return <div data-workflow="assist"><Intro eyebrow="Build with us" title="Bring one useful contribution.">Choose your lane. Each has a concrete outcome; you don’t need to be a developer.</Intro>
 <div className="grid gap-2 sm:grid-cols-2" aria-label="Contribution options">{contributions.map(c=><button key={c.id} onClick={()=>{setRole(c.id);setStatus('');}} aria-pressed={role===c.id} className={cn(action,'flex-col items-start text-left',role===c.id&&'bg-ink text-surface hover:bg-ink')}><span>{c.name}</span><span className="mt-1 text-xs font-normal leading-5">{c.brief}</span></button>)}</div>
 <section className="my-4 rounded-xl border border-line bg-canvas p-4"><h4 className="font-semibold">Your deliverable</h4><p className="mt-1 text-sm leading-6">{selected.outcome}</p><p className="mt-2 text-sm leading-6 text-muted">{selected.steps}</p><div className="mt-3"><Link href={selected.url}>{selected.link}</Link></div></section>
 <form onSubmit={save} noValidate className="space-y-3"><Field id={uid} label="What can you deliver?"><textarea id={uid} ref={ref} rows={3} maxLength={2000} className={input} value={details} onChange={e=>{setDetails(e.target.value);setStatus('');}} aria-invalid={!!error} aria-describedby={uid+'-error'}/></Field><p id={uid+'-error'} role="alert" className="text-sm">{error}</p><Callout>Keep personal contact details and private examples out of public posts. Review files return privately to your coordinator.</Callout><button className={action} type="submit">Download contribution</button><p role="status" className="text-sm">{status}</p></form><div className="mt-3"><Link href={repository+'/discussions/categories/general'}>Join the contributor discussion</Link></div></div>;
}
