import React,{useState} from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import {Intro,Link} from './shared.jsx';
const steps=[
 {name:'Observe',title:'Different questions. Different evidence.',body:'Each tag has its own job. Reference checks can compare claims with supplied sources; provenance checks can inspect origin records; risk checks can examine instructions and context. A tag can combine the sources, tools and methods its job requires.',example:'NF · Reference support\nMT · Manipulative framing\nPS · Scam / risk\nPA · Partial AI contribution',note:'These are distinct scope examples. Open a tag to see its current method and build status.'},
 {name:'Explain',title:'Several tags can belong to one answer.',body:'A reference-supported explanation can also include a risky command. One finding does not cancel the other. PS’s current command-risk preview does not establish whether the explanation is true, who wrote it, or whether the author intended a scam.',example:'NF   PS   PA',note:'Illustration of the intended multi-tag design, not an evaluated result. Small tags identify separate findings; selecting one explains its evidence.'},
 {name:'Challenge',title:'Each tag earns and keeps its own release.',body:'The method, evidence and version make the finding inspectable. Reproduction checks whether the method repeats its result; independent labels and other tag-appropriate tests check whether it performs its declared job. Corrections and unavailable checks stay with the affected tag.',example:'Question → evidence → tag → explanation → review',note:'PS is the first working preview. Other tags keep their own method, outcome and validation gate. A failed tag must not disable unrelated findings.'}
];
export default function HowTagsWork(){const [step,setStep]=useState('Observe');return <div data-workflow="how-tags-work"><Intro eyebrow="The complete tag system" title="One answer. Different findings.">Choose a tag to understand one finding. Each tag asks a different question and can draw on different sources, perspectives, engineering and tools.</Intro><Tabs.Root value={step} onValueChange={setStep}><Tabs.List aria-label="Tag explanation steps" className="flex flex-wrap gap-1 rounded-lg border border-line p-1">{steps.map((s,i)=><Tabs.Trigger key={s.name} value={s.name} className="min-h-11 min-w-0 flex-1 basis-20 wrap-anywhere rounded-md px-2 py-2 text-sm data-[state=active]:bg-ink data-[state=active]:text-surface">{i+1}. {s.name}</Tabs.Trigger>)}</Tabs.List>{steps.map(s=><Tabs.Content value={s.name} key={s.name} className="pt-4"><h4 className="text-xl font-semibold">{s.title}</h4><p className="mt-2 text-sm leading-6">{s.body}</p><div className="my-3 rounded-xl border border-input bg-canvas p-3"><p className="mb-2 text-xs text-muted">Design illustration</p><p className="whitespace-pre-wrap break-words text-sm font-semibold">{s.example}</p></div><p className="text-sm leading-6 text-muted">{s.note}</p></Tabs.Content>)}</Tabs.Root><div className="mt-4 flex flex-wrap gap-2"><Link href="/#person/PS" primary>Try the PS checker</Link><Link href="/#scope">Explore the full scope</Link><Link href="/tags/">Read each tag’s method</Link></div><p className="mt-3 text-xs leading-5 text-muted">Working previews, Building Now, Coming Soon and proposals show delivery status. Every tag must pass its own published validation gate before release.</p></div>;}
